default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload to Firebase App Distribution"
  lane :firebase do
    gradle(
            task: "bundle",
            build_type: "debug"
    )
    firebase_app_distribution(
        service_credentials_file: "./firebase-app-distribution.json",
        app: ENV["FIREBASE_APP_ID"],
        android_artifact_type: "AAB",
        groups: "internal-testers"
    )
  end

  desc "Deploy a new version to Google Play"
  lane :deploy do
    gradle(
        task: "bundle",
        build_type: "release"
    )
    upload_to_play_store(
        track: "internal",
        skip_upload_images: true,
        skip_upload_screenshots: true
    )
  end
end
