name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        GOOGLE_SERVICES_FILE: ${{ secrets.GOOGLE_SERVICES_FILE }}
      run: |
        echo $KEYSTORE_FILE | base64 -di > keystore.jks
        echo $GOOGLE_SERVICES_FILE | base64 -di > app/google-services.json

    - name: Assemble Apk
      env:
        KEYSTORE_PATH: ../keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assemble

    - name: Firebase App Distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      run: |
        curl -sL https://firebase.tools | bash
        firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
        --app $FIREBASE_APP_ID \
        --groups "Internal Testers"