name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish to Google Play
    runs-on: ubuntu-latest

    env:
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PATH: ../keystore.jks
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      GOOGLE_SERVICES_FILE: ${{ secrets.GOOGLE_SERVICES_FILE }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Decode Secrets
      run: |
        echo $KEYSTORE_FILE | base64 -di > keystore.jks
        echo $GOOGLE_SERVICES_FILE > app/google-services.json
        echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 -di > google-service-account.json

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true

    - name: Publish
      run: bundle exec fastlane deploy